### PR TITLE
Payments api

### PR DESCRIPTION
**Pull request by mtotodev05**
```
1. This request includes logic for Daraja API.
2. It contains tests.
3. I have run into  issues. encrypting multiple files with travis, i.e .env and service-account.json, Need Help

```

### CODE REVIEW

**Comment by mtotodev05** [comment]
I did try to encrypt them, for some reason, having two openssl commands, keeps failing, thats the help I need  😂😂

**Comment by michaelbukachi** [comment]
You can't have two. Only one works. So everything that needs to be encrypted should zipped up, encrypted, decrypted, unzipped and copied to the necessary location.

**Comment by mtotodev05** [comment]
` The command "openssl aes-256-cbc -K $encrypted_5880cf525281_key -iv $encrypted_5880cf525281_iv -in credentials.tar.enc -out credentials.tar -d" failed and exited with 1 during .`

**Comment by mtotodev05** [comment]
> Did you just put the daraja keys in the .env file?

Requested changes have been implemented

**Pull request merged**
